### ISSUE TITLE
Closed Ticket Access Issue: Users Unable to Open New Tickets After Closure

### ISSUE THREAD

**Issue by KoreMoDz** [Sayrix/Ticket-Bot#323] opened 2024-01-12 00:48 UTC
**Describe the bug**
There's a bug in the Discord ticket bot system. When a user's ticket is closed but not deleted, they are unable to open new tickets. The chat created for the ticket becomes inaccessible, or an error message indicates that the ticket limit is one, even though they have no open tickets. This issue occurs specifically when a ticket is closed, and the user tries to reopen it using the same message that is only visible to them.

**To Reproduce**
1. Close a user's ticket without deleting it.
2. The user tries to open a new ticket by clicking on the message that was used to open the previously closed ticket, which is only visible to them.
3. The chat for the new ticket becomes inaccessible to the user.
4. Alternatively, an error message is displayed indicating a ticket limit of one, despite no open tickets.

**Expected behavior**
After a ticket is closed, users should be able to open new tickets without encountering access issues or receiving incorrect ticket limit errors.

https://github.com/Sayrix/Ticket-Bot/assets/135083201/42b01180-bd8a-459e-b72f-06fe36a237db

**Comment by zhiyan114** [comment] 2024-02-11 01:12
Hi,

I wasn't able to reproduce the said issue, by both testing and reviewing the query that counts for the total open tickets. Could it be that the issue is already fixed in the `feat` branch and haven't been pushed to the main yet?

**Comment by zhiyan114** [comment] 2024-02-15 20:45
Closed due to lack of update from user

**Closed by zhiyan114** 2024-02-15 20:45 UTC
Labels: bug
